global_settings:
  forecast_horizon: 21
  optimization_date: '2025-07-11'
  total_combinations_tested: 100
  best_combined_score: 0.523
  mathematical_consistency: true
horizon_21_parameters:
  volatility:
    us_large_equity:
      method: ewma
      lambda: 0.94
      min_periods: 30
      validation_score: 0.023
      sample_size: 500
    us_small_equity:
      method: ewma
      lambda: 0.92
      min_periods: 30
      validation_score: 0.031
      sample_size: 480
    government_bonds:
      method: ewma
      lambda: 0.96
      min_periods: 30
      validation_score: 0.018
      sample_size: 520
  correlation:
    method: ewma
    lambda: 0.95
    min_periods: 60
    validation_score: 0.142
    sample_size: 450
validation_summary:
  volatility_performance:
    best_mse: 0.018
    worst_mse: 0.031
    average_mse: 0.024
    exposures_improved: 3
  correlation_performance:
    best_frobenius_norm: 0.142
    improvement_vs_sample: 0.23
