horizon_252_results:
  correlation_parameters:
    horizon: 252
    parameters:
      lookback_days: 504
      method: historical
      min_periods: 120
    validation_score: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      QRm0wq6kEEA=
  goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    DGSrDy0z0z8=
  portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    uNpszOGwVz8=
  return_accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAA8D8=
  return_parameters:
    broad_ust:
      horizon: 252
      method: historical
      parameters:
        lookback_days: 126
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA6D8=
    cash_rate:
      horizon: 252
      method: historical
      parameters:
        lookback_days: 126
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    commodities:
      horizon: 252
      method: ewma
      parameters:
        decay_factor: 0.9
        lookback_days: 252
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    dynamic_global_bonds:
      horizon: 252
      method: ewma
      parameters:
        decay_factor: 0.9
        lookback_days: 252
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        VVVVVVVV5T8=
    emerging_equity:
      horizon: 252
      method: ewma
      parameters:
        decay_factor: 0.95
        lookback_days: 252
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    factor_style_equity:
      horizon: 252
      method: ewma
      parameters:
        decay_factor: 0.9
        lookback_days: 504
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    factor_style_other:
      horizon: 252
      method: ewma
      parameters:
        decay_factor: 0.95
        lookback_days: 252
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    global_macro:
      horizon: 252
      method: historical
      parameters:
        lookback_days: 126
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA4D8=
    gold:
      horizon: 252
      method: ewma
      parameters:
        decay_factor: 0.9
        lookback_days: 504
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    intl_developed_large_equity:
      horizon: 252
      method: momentum
      parameters:
        lookback_days: 252
        min_periods: 30
        momentum_period: 3
        momentum_strength: 0.5
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    intl_developed_small_equity:
      horizon: 252
      method: mean_reversion
      parameters:
        lookback_days: 504
        min_periods: 30
        recent_period: 12
        reversion_strength: 0.3
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    real_estate:
      horizon: 252
      method: mean_reversion
      parameters:
        lookback_days: 504
        min_periods: 30
        recent_period: 12
        reversion_strength: 0.3
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    short_ust:
      horizon: 252
      method: ewma
      parameters:
        decay_factor: 0.9
        lookback_days: 504
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    tips:
      horizon: 252
      method: mean_reversion
      parameters:
        lookback_days: 504
        min_periods: 30
        recent_period: 6
        reversion_strength: 0.5
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    trend_following:
      horizon: 252
      method: historical
      parameters:
        lookback_days: 126
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    us_large_equity:
      horizon: 252
      method: momentum
      parameters:
        lookback_days: 252
        min_periods: 30
        momentum_period: 3
        momentum_strength: 0.8
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
    us_small_equity:
      horizon: 252
      method: mean_reversion
      parameters:
        lookback_days: 252
        min_periods: 30
        recent_period: 12
        reversion_strength: 0.5
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA8D8=
  volatility_parameters:
    broad_ust:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.94
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        u1UoXf/zBz4=
    cash_rate:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.97
        lookback_days: 252
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        mqfcwUpz/T0=
    commodities:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.94
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        LHkqyyvM5z4=
    dynamic_global_bonds:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.97
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        ix/AJJJstD0=
    emerging_equity:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        nVgcWdGo2j4=
    factor_style_equity:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        uNzUZ5NxoD4=
    factor_style_other:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        aEBUOvluVT4=
    global_macro:
      horizon: 252
      method: historical
      parameters:
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        v/YXpm5wYD4=
    gold:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        q3ufYuOofT4=
    intl_developed_large_equity:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        u27fVwDe0z4=
    intl_developed_small_equity:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        vr4VRTYU0D4=
    real_estate:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        qqbTsDkjkD4=
    short_ust:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.99
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        XLKgGbpsej4=
    tips:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        fdwLojBUKT4=
    trend_following:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.97
        lookback_days: 504
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        /Gm4voFYOT4=
    us_large_equity:
      horizon: 252
      method: historical
      parameters:
        lookback_days: 504
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        WJr7zQED4j4=
    us_small_equity:
      horizon: 252
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        E/ka9BWerz4=
horizon_comparison:
  10_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      N7BQafNbxD8=
    portfolio_rmse: 0.0
  126_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      a+grAK1tyz8=
    portfolio_rmse: 0.0
  189_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      7rY9yYHrwT8=
    portfolio_rmse: 0.0
  21_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      NmxPOWCCyD8=
    portfolio_rmse: 0.0
  252_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      DGSrDy0z0z8=
    portfolio_rmse: 0.0
  365_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      w3qLloKZuT8=
    portfolio_rmse: 0.0
  42_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      jA+Bkyhvyj8=
    portfolio_rmse: 0.0
  5_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      d/Ec4rGLxT8=
    portfolio_rmse: 0.0
  63_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      2JTAkftzyj8=
    portfolio_rmse: 0.0
optimal_horizon: 252
optimization_metadata:
  candidate_horizons:
  - 5
  - 10
  - 21
  - 42
  - 63
  - 126
  - 189
  - 252
  - 365
  method: portfolio_level_two_stage
  optimization_date: '2025-07-14'
  test_portfolios: 3
