horizon_189_results:
  correlation_parameters:
    horizon: 189
    parameters:
      lookback_days: 504
      method: historical
      min_periods: 120
    validation_score: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      LR0a/W0tDkA=
  goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    fEhSEsQNo74=
  portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    cj2SP0mxSD8=
  volatility_parameters:
    broad_ust:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        j3q4mSr6aD4=
    cash_rate:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.97
        lookback_days: 504
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        PxBk+Brw4z0=
    commodities:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.94
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        Dm7ykWNQ4T4=
    dynamic_global_bonds:
      horizon: 189
      method: historical
      parameters:
        lookback_days: 504
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        DwYirZGfUj4=
    emerging_equity:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        oIQb/NLc0j4=
    factor_style_equity:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.97
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        9G3/Jm7owz4=
    factor_style_other:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.97
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        rij+SePOwD4=
    global_macro:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.94
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        Mlx1pAyYoz4=
    gold:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.99
        lookback_days: 504
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        sLx+e+ZDvj4=
    intl_developed_large_equity:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        Sec40OsUyj4=
    intl_developed_small_equity:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 252
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        rq85TsFezD4=
    real_estate:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        YQKtCis/tj4=
    short_ust:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.97
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        KmlTOXP3gD4=
    tips:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.94
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        +WYsTolWhj4=
    trend_following:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.97
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        27Yv3HFrhj4=
    us_large_equity:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        CppqQeXr4D4=
    us_small_equity:
      horizon: 189
      method: ewma
      parameters:
        lambda: 0.9
        lookback_days: 756
        min_periods: 30
      validation_score: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        7hhGaE6l0j4=
horizon_comparison:
  10_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      3ylx0OQHCr8=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      EHiJ4YvcfD8=
  126_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      ElPO8v8rvL4=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      EvS5hRo7VT8=
  189_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      fEhSEsQNo74=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      cj2SP0mxSD8=
  21_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      z/oepWXC774=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      lRBN8SPhbz8=
  252_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      nDub5dCIwb4=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      nthuAgawVz8=
  365_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      N9qzkc5wwL4=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      fk9P8NfvVj8=
  42_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      d81Zz+qo2r4=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      ilRuVDynZD8=
  5_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      De3Rdb1ZJL8=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      2m+aztqEiT8=
  63_day:
    goodness_score: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      PULau8LYyb4=
    portfolio_rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      sqVY617CXD8=
optimal_horizon: 189
optimization_metadata:
  candidate_horizons:
  - 5
  - 10
  - 21
  - 42
  - 63
  - 126
  - 189
  - 252
  - 365
  method: portfolio_level_two_stage
  optimization_date: '2025-07-14'
  test_portfolios: 3
